
//
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
//

using System.Reflection;


[assembly: AssemblyTitle("LiveCaptions Translator")]
[assembly: AssemblyVersion("1.1.1251.2619")]
[assembly: AssemblyFileVersion("1.1.1251.2619")]